apiVersion: v1
kind: ConfigMap
metadata:
  name: paralus-config
  labels:
    {{- include "ztka.labels" . | nindent 4 }}
    {{- include "ztka.selectorLabels" (dict "image" $.Values.images.paralus "release" $.Release) | nindent 4 }}
data:
  DEV: "false"
  AUDIT_LOG_FILE: "/audit-logs/audit.log"
  AUDIT_LOG_STORAGE: {{ include "ztka.auditlogStorage" . | quote }}
  ES_INDEX_PREFIX: "{{ .Values.deploy.filebeat.indexPrefix }}-system"
  RELAY_AUDITS_ES_INDEX_PREFIX: "{{ .Values.deploy.filebeat.indexPrefix }}-relay"
  RELAY_COMMANDS_ES_INDEX_PREFIX: "{{ .Values.deploy.filebeat.indexPrefix }}-prompt"
  ES_END_POINT: {{ include "ztka.esAddr" . | quote }}
  KRATOS_ADDR: {{ include "ztka.kratos.adminAddr" . | quote }}
  KRATOS_PUB_ADDR: {{ include "ztka.kratos.publicAddr" . | quote }}
  RELAY_IMAGE: {{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag | default .Chart.AppVersion }}
  SCHEDULER_NAMESPACE: {{ .Release.Namespace | quote }}
  SENTRY_PEERING_HOST: "paralus:10001"
  CORE_RELAY_CONNECTOR_HOST: {{ printf "%s:%s" (include "ztka.coreConnectorFQDN" .) "443" | quote }}
  CORE_RELAY_USER_HOST: {{ printf "%s:%s" (include "ztka.userFQDN" .) "443" | quote }}
  SENTRY_BOOTSTRAP_ADDR: {{ include "ztka.consoleFQDNWithPort" . | quote }}
